extends Node

## GameManager.gd
## Autoload singleton (add via Project Settings > Autoload).
## Central place for fight tracking, run state, and later: calling into the
## enchant recommender lookup table (Week 9-10).

var current_run_seed: int = 0
var fight_start_time: float = 0.0

# Placeholder for the exported k-NN decision table (Week 9-10).
# Will be loaded from res://data/enchant_lookup.json once generated by the
# Python training script.
var enchant_lookup: Dictionary = {}


func _ready() -> void:
	randomize()
	current_run_seed = randi()
	_load_enchant_lookup()


func start_fight() -> void:
	fight_start_time = Time.get_ticks_msec() / 1000.0


func end_fight(player: Node) -> Dictionary:
	var duration := (Time.get_ticks_msec() / 1000.0) - fight_start_time
	var profile: Dictionary = player.get_playstyle_profile(duration)
	print("Fight ended. Player profile: ", profile)
	return profile


func _load_enchant_lookup() -> void:
	var path := "res://data/enchant_lookup.json"
	if not FileAccess.file_exists(path):
		print("Enchant lookup table not found yet (expected until Week 9-10).")
		return
	var file := FileAccess.open(path, FileAccess.READ)
	var content := file.get_as_text()
	var parsed = JSON.parse_string(content)
	if parsed != null:
		enchant_lookup = parsed
		print("Loaded enchant lookup table with ", enchant_lookup.size(), " entries.")


## Given a player profile (see Player.get_playstyle_profile), find the
## nearest matching entry in the lookup table and return its recommended
## enchant. Real nearest-neighbor logic will be filled in once the table
## exists — for now this is a stub so other systems can integrate against
## a stable interface.
func recommend_enchant(profile: Dictionary) -> String:
	if enchant_lookup.is_empty():
		return "balanced_damage" # safe default fallback
	# TODO (Week 9-10): implement nearest-neighbor lookup against enchant_lookup
	return "balanced_damage"
