extends Node

## GameManager.gd
## Autoload singleton (add via Project Settings > Autoload).
## Central place for fight tracking, run state, and later: calling into the
## enchant recommender lookup table (Week 9-10).

var current_run_seed: int = 0
var _fight_start_time: float = 0.0
var last_skill_tier: String = "Average"
var attempts_this_boss: int = 1
var currency: int = 0 
var equipped_enchant: String = ""

const FIGHT_LOG_PATH := "user://fight_logs.json"

#currency on shop UI 
func add_currency(amount: int) -> void:
	currency+=amount
	print("Gained: ", amount, "gold. Total: ", currency)

func equip_enchant(enchant_name: String) -> void:
	equipped_enchant = enchant_name
	print("Equipped enchant: ", enchant_name)

# Placeholder for the exported k-NN decision table (Week 9-10).
# Will be loaded from res://data/enchant_lookup.json once generated by the
# Python training script.
var enchant_lookup: Dictionary = {}


func _ready() -> void:
	randomize()
	current_run_seed = randi()
	_load_enchant_lookup()


func start_fight() -> void:
	_fight_start_time = Time.get_ticks_msec() / 1000.0

func get_fight_duration() -> float:
	return (Time.get_ticks_msec() / 1000.0) - _fight_start_time

func end_fight(player: Node) -> Dictionary:
	var duration := (Time.get_ticks_msec() / 1000.0) - _fight_start_time
	var profile: Dictionary = player.get_playstyle_profile(duration)
	print("Fight ended. Player profile: ", profile)
	return profile


func _load_enchant_lookup() -> void:
	var path := "res://data/enchant_lookup.json"
	if not FileAccess.file_exists(path):
		print("Enchant lookup table not found yet (expected until Week 9-10).")
		return
	var file := FileAccess.open(path, FileAccess.READ)
	var content := file.get_as_text()
	var parsed = JSON.parse_string(content)
	if parsed != null:
		enchant_lookup = parsed
		print("Loaded enchant lookup table with ", enchant_lookup.get("dataset", []).size(), " entries.")
# --- Real fight-data logging (Week 9-10) ---
# Add these pieces into the EXISTING GameManager.gd -- don't replace the
# whole file. This integrates with your existing start_fight()/end_fight().
#
# GameManager already tracks fight duration via _fight_start_time and
# builds `profile` (dodge_rate, hit_taken_rate, avg_fight_duration,
# damage_dealt_avg) inside end_fight(). This just adds:
#   1. an `attempts` counter (per-boss, resets on victory or new boss)
#   2. writing the completed profile + attempts to user://fight_logs.json
#
# Logs persist across play sessions. To feed them into the Python merge
# script, copy the file out to your project folder as
# "player_fight_logs.json" and run merge_real_data.py.
#
# On Windows, user:// typically lives at:
#   %APPDATA%\Godot\app_userdata\Dungeon Hunter\fight_logs.json




func log_fight_result(profile: Dictionary) -> void:
	var entry := {
		"dodge_rate": profile["dodge_rate"],
		"hit_taken_rate": profile["hit_taken_rate"],
		"avg_fight_duration": profile["avg_fight_duration"],
		"damage_dealt_avg": profile["damage_dealt_avg"],
		"attempts": attempts_this_boss,
	}

	var logs: Array = []
	if FileAccess.file_exists(FIGHT_LOG_PATH):
		var read_file := FileAccess.open(FIGHT_LOG_PATH, FileAccess.READ)
		var parsed = JSON.parse_string(read_file.get_as_text())
		if parsed is Array:
			logs = parsed
		read_file.close()

	logs.append(entry)

	var write_file := FileAccess.open(FIGHT_LOG_PATH, FileAccess.WRITE)
	write_file.store_string(JSON.stringify(logs, "\t"))
	write_file.close()

	print("Logged fight result (", logs.size(), " total logged fights).")


# --- Call sites (wire these into existing flow) ---
#
# When the player DIES against the boss (fight lost -- attempt failed):
#   attempts_this_boss += 1
#   (don't log this one -- only log completed/won fights, since a loss
#    doesn't have a real "time_to_defeat"; or, if you want losses logged
#    too, call log_fight_result() here as well -- optional, your call)
#
# When the BOSS DIES (fight won):
#   var profile = end_fight(player)     # already builds the profile dict
#   log_fight_result(profile)
#   attempts_this_boss = 1               # reset for the next boss encounter

## Given a player profile (see Player.get_playstyle_profile), find the
## nearest matching entry in the lookup table and return its recommended
## enchant. Real nearest-neighbor logic will be filled in once the table
## exists — for now this is a stub so other systems can integrate against
## a stable interface.
func recommend_enchant(profile: Dictionary) -> String:
	if enchant_lookup.is_empty() or not enchant_lookup.has("dataset"):
		return "balanced_damage" # safe default fallback

	var feature_order: Array = enchant_lookup["feature_order"]
	var mins: Dictionary = enchant_lookup["normalization"]["min"]
	var maxs: Dictionary = enchant_lookup["normalization"]["max"]
	var k: int = enchant_lookup.get("k", 5)
	var dataset: Array = enchant_lookup["dataset"]

	# Build and normalize the live query vector (attempts comes from GameManager itself)
	var query: Array = []
	for name in feature_order:
		var raw: float = profile.get(name, attempts_this_boss if name == "attempts" else 0.0)
		var lo: float = mins[name]
		var hi: float = maxs[name]
		var norm: float = 0.0 if hi == lo else (raw - lo) / (hi - lo)
		query.append(norm)

	# Compute distance to every point, normalized the same way
	var distances: Array = []
	for point in dataset:
		var feats: Dictionary = point["features"]
		var dist_sq: float = 0.0
		for i in range(feature_order.size()):
			var name = feature_order[i]
			var lo: float = mins[name]
			var hi: float = maxs[name]
			var raw: float = feats[name]
			var norm: float = 0.0 if hi == lo else (raw - lo) / (hi - lo)
			var diff: float = query[i] - norm
			dist_sq += diff * diff
		distances.append({"dist": dist_sq, "enchant": point["enchant"], "tier": point["tier"]})

	distances.sort_custom(func(a, b): return a["dist"] < b["dist"])

	# Majority vote over k nearest for enchant
	var enchant_votes: Dictionary = {}
	var tier_votes: Dictionary = {}
	for i in range(min(k, distances.size())):
		var e = distances[i]["enchant"]
		var t = distances[i]["tier"]
		enchant_votes[e] = enchant_votes.get(e, 0) + 1
		tier_votes[t] = tier_votes.get(t, 0) + 1

	last_skill_tier = _majority(tier_votes)  # store for BossAI to read
	return _majority(enchant_votes)


func _majority(votes: Dictionary) -> String:
	var best_key := ""
	var best_count := -1
	for key in votes:
		if votes[key] > best_count:
			best_count = votes[key]
			best_key = key
	return best_key
